### ISSUE TITLE
Tiny misprint in Teensy instructions

### ISSUE THREAD

**Issue by dkazdan** [RobTillaart/Complex#3]
Thank you for providing all of this.

Note that in the Teensy installation instructions, there is a one-letter typo:

Solution:
Make a copy of the Complex Library and rename the folder to CComplex
Rename Complex.h to CComplex.h
Rename Complex.cpp to CComplec.cpp                // this line--should be CComplex.cpp rather than CComplec.cpp
change one line in CComplex.cpp to include CComplex.h

73,

David

**Comment by RobTillaart** [comment]
Thanks for pointing out, I will fix this asap

**Comment by RobTillaart** [comment]
An update is under way, build-CI is fixed and some small edits including cosmetic ones.

**Comment by dkazdan** [comment]
Thank you!

And again, thank you for supplying the library. It's a real help to our work.

David

David Kazdan
Case Western Reserve University
Cleveland, Ohio

**Comment by RobTillaart** [comment]
May I ask what kind of projects / research you use the library for?
